spring:
 datasource:
  username: root
  password: Teju@12345
  url: jdbc:mysql://localhost:3306/tejudb
  driver-class-name: com.mysql.cj.jdbc.Driver
  
  
 spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true  
    